# Array of commit messages (no accents to avoid PowerShell UTF-8 issues)
$commits = @(
"Initialisation du module Medecin dans le projet Flask",
"Creation de la route medecin/dashboard",
"Creation de la route medecin/list pour afficher les medecins",
"Creation de la route medecin/add pour ajouter un medecin",
"Creation de la route medecin/edit/<id> pour editer un medecin",
"Creation de la route medecin/delete/<id> pour supprimer un medecin",
"Ajout du modele Medecin avec attributs de base",
"Ajout des methodes CRUD dans le modele Medecin",
"Ajout de la connexion a la base de donnees pour les medecins",
"Gestion des exceptions lors des operations sur Medecin",
"Creation du template medecin_list.html",
"Creation du template medecin_add.html",
"Creation du template medecin_edit.html",
"Ajout des boutons Edit/Delete sur la liste des medecins",
"Ajout du formulaire d ajout medecin",
"Ajout du formulaire d edition medecin",
"Affichage dynamique des medecins depuis la base",
"Correction des colonnes et titres dans la liste des medecins",
"Mise en page des boutons cote a cote",
"Augmentation de la taille des boutons pour visibilite",
"Ajout de messages flash lors de l ajout medecin",
"Ajout de messages flash lors de l edition medecin",
"Ajout de messages flash lors de la suppression medecin",
"Validation cote serveur ajout medecin",
"Validation cote serveur edition medecin",
"Gestion 404 medecin non trouve",
"Gestion erreurs DB medecin",
"Optimisation des imports medecin_routes",
"Nettoyage du modele Medecin",
"Ajout de commentaires routes Medecin",
"Ajout CSS uniformisation tableau medecins",
"Ajout CSS amelioration boutons medecin",
"Responsive pour tableau medecins",
"Test fonctionnel route medecin/list",
"Test fonctionnel route medecin/add",
"Test fonctionnel route medecin/edit",
"Test fonctionnel route medecin/delete",
"Correction bug affichage medecin_list.html",
"Correction validation ajout medecin",
"Correction validation edition medecin",
"Gestion des doublons ajout medecin",
"Ajout pagination medecins",
"Ajout recherche medecins",
"Ajout filtre specialite",
"Amelioration medecin_add placeholders",
"Amelioration medecin_edit placeholders",
"Ajout icones Edit/Delete",
"Mise a jour README module Medecin",
"Nettoyage fichiers temporaires Medecin",
"Preparation module Medecin pour push",
"Ajout tests unitaires modele Medecin",
"Ajout tests unitaires route add",
"Ajout tests unitaires route edit",
"Ajout tests unitaires route delete",
"Ajout logs actions CRUD Medecin",
"Gestion messages erreur operations invalides",
"Optimisation requetes SQL",
"Amelioration lisibilite templates Medecin",
"Ajout notifications JS suppression medecin",
"Correction bug edition medecin existant",
"Verification affichage apres ajout/edition",
"Verification affichage apres suppression",
"Test complet module Medecin",
"Correction finale bugs",
"Refactorisation code medecin",
"Ajout commentaires finaux",
"Nettoyage final CSS",
"Preparation commits avant push",
"Commit final module Medecin stable"
)

Write-Host "== Execution des commits =="

foreach ($msg in $commits) {
    git add .
    git commit -m "$msg"
    Write-Host "OK: $msg"
}

Write-Host "== Tous les commits ont ete crees =="
